# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/qtran/CPLUSPLUS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/qtran/CPLUSPLUS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/qtran/CPLUSPLUS/CMakeFiles /home/qtran/CPLUSPLUS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/qtran/CPLUSPLUS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

TestBalanceRedBlackTree.o: TestBalanceRedBlackTree.cpp.o

.PHONY : TestBalanceRedBlackTree.o

# target to build an object file
TestBalanceRedBlackTree.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestBalanceRedBlackTree.cpp.o
.PHONY : TestBalanceRedBlackTree.cpp.o

TestBalanceRedBlackTree.i: TestBalanceRedBlackTree.cpp.i

.PHONY : TestBalanceRedBlackTree.i

# target to preprocess a source file
TestBalanceRedBlackTree.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestBalanceRedBlackTree.cpp.i
.PHONY : TestBalanceRedBlackTree.cpp.i

TestBalanceRedBlackTree.s: TestBalanceRedBlackTree.cpp.s

.PHONY : TestBalanceRedBlackTree.s

# target to generate assembly for a file
TestBalanceRedBlackTree.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestBalanceRedBlackTree.cpp.s
.PHONY : TestBalanceRedBlackTree.cpp.s

TestClosestPairOfPointsOnPlane.o: TestClosestPairOfPointsOnPlane.cpp.o

.PHONY : TestClosestPairOfPointsOnPlane.o

# target to build an object file
TestClosestPairOfPointsOnPlane.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestClosestPairOfPointsOnPlane.cpp.o
.PHONY : TestClosestPairOfPointsOnPlane.cpp.o

TestClosestPairOfPointsOnPlane.i: TestClosestPairOfPointsOnPlane.cpp.i

.PHONY : TestClosestPairOfPointsOnPlane.i

# target to preprocess a source file
TestClosestPairOfPointsOnPlane.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestClosestPairOfPointsOnPlane.cpp.i
.PHONY : TestClosestPairOfPointsOnPlane.cpp.i

TestClosestPairOfPointsOnPlane.s: TestClosestPairOfPointsOnPlane.cpp.s

.PHONY : TestClosestPairOfPointsOnPlane.s

# target to generate assembly for a file
TestClosestPairOfPointsOnPlane.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestClosestPairOfPointsOnPlane.cpp.s
.PHONY : TestClosestPairOfPointsOnPlane.cpp.s

TestLongestIncreasingSub.o: TestLongestIncreasingSub.cpp.o

.PHONY : TestLongestIncreasingSub.o

# target to build an object file
TestLongestIncreasingSub.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestLongestIncreasingSub.cpp.o
.PHONY : TestLongestIncreasingSub.cpp.o

TestLongestIncreasingSub.i: TestLongestIncreasingSub.cpp.i

.PHONY : TestLongestIncreasingSub.i

# target to preprocess a source file
TestLongestIncreasingSub.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestLongestIncreasingSub.cpp.i
.PHONY : TestLongestIncreasingSub.cpp.i

TestLongestIncreasingSub.s: TestLongestIncreasingSub.cpp.s

.PHONY : TestLongestIncreasingSub.s

# target to generate assembly for a file
TestLongestIncreasingSub.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestLongestIncreasingSub.cpp.s
.PHONY : TestLongestIncreasingSub.cpp.s

TestPriorityQueueBinaryHeap.o: TestPriorityQueueBinaryHeap.cpp.o

.PHONY : TestPriorityQueueBinaryHeap.o

# target to build an object file
TestPriorityQueueBinaryHeap.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestPriorityQueueBinaryHeap.cpp.o
.PHONY : TestPriorityQueueBinaryHeap.cpp.o

TestPriorityQueueBinaryHeap.i: TestPriorityQueueBinaryHeap.cpp.i

.PHONY : TestPriorityQueueBinaryHeap.i

# target to preprocess a source file
TestPriorityQueueBinaryHeap.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestPriorityQueueBinaryHeap.cpp.i
.PHONY : TestPriorityQueueBinaryHeap.cpp.i

TestPriorityQueueBinaryHeap.s: TestPriorityQueueBinaryHeap.cpp.s

.PHONY : TestPriorityQueueBinaryHeap.s

# target to generate assembly for a file
TestPriorityQueueBinaryHeap.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestPriorityQueueBinaryHeap.cpp.s
.PHONY : TestPriorityQueueBinaryHeap.cpp.s

TestRandomizedQuickSorted.o: TestRandomizedQuickSorted.cpp.o

.PHONY : TestRandomizedQuickSorted.o

# target to build an object file
TestRandomizedQuickSorted.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestRandomizedQuickSorted.cpp.o
.PHONY : TestRandomizedQuickSorted.cpp.o

TestRandomizedQuickSorted.i: TestRandomizedQuickSorted.cpp.i

.PHONY : TestRandomizedQuickSorted.i

# target to preprocess a source file
TestRandomizedQuickSorted.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestRandomizedQuickSorted.cpp.i
.PHONY : TestRandomizedQuickSorted.cpp.i

TestRandomizedQuickSorted.s: TestRandomizedQuickSorted.cpp.s

.PHONY : TestRandomizedQuickSorted.s

# target to generate assembly for a file
TestRandomizedQuickSorted.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestRandomizedQuickSorted.cpp.s
.PHONY : TestRandomizedQuickSorted.cpp.s

TestmajorityElementValidate.o: TestmajorityElementValidate.cpp.o

.PHONY : TestmajorityElementValidate.o

# target to build an object file
TestmajorityElementValidate.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestmajorityElementValidate.cpp.o
.PHONY : TestmajorityElementValidate.cpp.o

TestmajorityElementValidate.i: TestmajorityElementValidate.cpp.i

.PHONY : TestmajorityElementValidate.i

# target to preprocess a source file
TestmajorityElementValidate.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestmajorityElementValidate.cpp.i
.PHONY : TestmajorityElementValidate.cpp.i

TestmajorityElementValidate.s: TestmajorityElementValidate.cpp.s

.PHONY : TestmajorityElementValidate.s

# target to generate assembly for a file
TestmajorityElementValidate.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/TestmajorityElementValidate.cpp.s
.PHONY : TestmajorityElementValidate.cpp.s

longestIncreasingSub.o: longestIncreasingSub.cpp.o

.PHONY : longestIncreasingSub.o

# target to build an object file
longestIncreasingSub.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/longestIncreasingSub.cpp.o
.PHONY : longestIncreasingSub.cpp.o

longestIncreasingSub.i: longestIncreasingSub.cpp.i

.PHONY : longestIncreasingSub.i

# target to preprocess a source file
longestIncreasingSub.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/longestIncreasingSub.cpp.i
.PHONY : longestIncreasingSub.cpp.i

longestIncreasingSub.s: longestIncreasingSub.cpp.s

.PHONY : longestIncreasingSub.s

# target to generate assembly for a file
longestIncreasingSub.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/longestIncreasingSub.cpp.s
.PHONY : longestIncreasingSub.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/main.cpp.s
.PHONY : main.cpp.s

majorityElementValidate.o: majorityElementValidate.cpp.o

.PHONY : majorityElementValidate.o

# target to build an object file
majorityElementValidate.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/majorityElementValidate.cpp.o
.PHONY : majorityElementValidate.cpp.o

majorityElementValidate.i: majorityElementValidate.cpp.i

.PHONY : majorityElementValidate.i

# target to preprocess a source file
majorityElementValidate.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/majorityElementValidate.cpp.i
.PHONY : majorityElementValidate.cpp.i

majorityElementValidate.s: majorityElementValidate.cpp.s

.PHONY : majorityElementValidate.s

# target to generate assembly for a file
majorityElementValidate.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/majorityElementValidate.cpp.s
.PHONY : majorityElementValidate.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... edit_cache"
	@echo "... TestBalanceRedBlackTree.o"
	@echo "... TestBalanceRedBlackTree.i"
	@echo "... TestBalanceRedBlackTree.s"
	@echo "... TestClosestPairOfPointsOnPlane.o"
	@echo "... TestClosestPairOfPointsOnPlane.i"
	@echo "... TestClosestPairOfPointsOnPlane.s"
	@echo "... TestLongestIncreasingSub.o"
	@echo "... TestLongestIncreasingSub.i"
	@echo "... TestLongestIncreasingSub.s"
	@echo "... TestPriorityQueueBinaryHeap.o"
	@echo "... TestPriorityQueueBinaryHeap.i"
	@echo "... TestPriorityQueueBinaryHeap.s"
	@echo "... TestRandomizedQuickSorted.o"
	@echo "... TestRandomizedQuickSorted.i"
	@echo "... TestRandomizedQuickSorted.s"
	@echo "... TestmajorityElementValidate.o"
	@echo "... TestmajorityElementValidate.i"
	@echo "... TestmajorityElementValidate.s"
	@echo "... longestIncreasingSub.o"
	@echo "... longestIncreasingSub.i"
	@echo "... longestIncreasingSub.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... majorityElementValidate.o"
	@echo "... majorityElementValidate.i"
	@echo "... majorityElementValidate.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

