# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding

# Include any dependencies generated for this target.
include CMakeFiles/sample.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/sample.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/sample.dir/flags.make

CMakeFiles/sample.dir/TestLongestIncreasingSub.cpp.o: CMakeFiles/sample.dir/flags.make
CMakeFiles/sample.dir/TestLongestIncreasingSub.cpp.o: TestLongestIncreasingSub.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/sample.dir/TestLongestIncreasingSub.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/sample.dir/TestLongestIncreasingSub.cpp.o -c /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/TestLongestIncreasingSub.cpp

CMakeFiles/sample.dir/TestLongestIncreasingSub.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sample.dir/TestLongestIncreasingSub.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/TestLongestIncreasingSub.cpp > CMakeFiles/sample.dir/TestLongestIncreasingSub.cpp.i

CMakeFiles/sample.dir/TestLongestIncreasingSub.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sample.dir/TestLongestIncreasingSub.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/TestLongestIncreasingSub.cpp -o CMakeFiles/sample.dir/TestLongestIncreasingSub.cpp.s

CMakeFiles/sample.dir/longestIncreasingSub.cpp.o: CMakeFiles/sample.dir/flags.make
CMakeFiles/sample.dir/longestIncreasingSub.cpp.o: longestIncreasingSub.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/sample.dir/longestIncreasingSub.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/sample.dir/longestIncreasingSub.cpp.o -c /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/longestIncreasingSub.cpp

CMakeFiles/sample.dir/longestIncreasingSub.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sample.dir/longestIncreasingSub.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/longestIncreasingSub.cpp > CMakeFiles/sample.dir/longestIncreasingSub.cpp.i

CMakeFiles/sample.dir/longestIncreasingSub.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sample.dir/longestIncreasingSub.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/longestIncreasingSub.cpp -o CMakeFiles/sample.dir/longestIncreasingSub.cpp.s

CMakeFiles/sample.dir/TestRandomizedQuickSorted.cpp.o: CMakeFiles/sample.dir/flags.make
CMakeFiles/sample.dir/TestRandomizedQuickSorted.cpp.o: TestRandomizedQuickSorted.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/sample.dir/TestRandomizedQuickSorted.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/sample.dir/TestRandomizedQuickSorted.cpp.o -c /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/TestRandomizedQuickSorted.cpp

CMakeFiles/sample.dir/TestRandomizedQuickSorted.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sample.dir/TestRandomizedQuickSorted.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/TestRandomizedQuickSorted.cpp > CMakeFiles/sample.dir/TestRandomizedQuickSorted.cpp.i

CMakeFiles/sample.dir/TestRandomizedQuickSorted.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sample.dir/TestRandomizedQuickSorted.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/TestRandomizedQuickSorted.cpp -o CMakeFiles/sample.dir/TestRandomizedQuickSorted.cpp.s

CMakeFiles/sample.dir/RandomizedQuickSorted.cpp.o: CMakeFiles/sample.dir/flags.make
CMakeFiles/sample.dir/RandomizedQuickSorted.cpp.o: RandomizedQuickSorted.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/sample.dir/RandomizedQuickSorted.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/sample.dir/RandomizedQuickSorted.cpp.o -c /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/RandomizedQuickSorted.cpp

CMakeFiles/sample.dir/RandomizedQuickSorted.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sample.dir/RandomizedQuickSorted.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/RandomizedQuickSorted.cpp > CMakeFiles/sample.dir/RandomizedQuickSorted.cpp.i

CMakeFiles/sample.dir/RandomizedQuickSorted.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sample.dir/RandomizedQuickSorted.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/RandomizedQuickSorted.cpp -o CMakeFiles/sample.dir/RandomizedQuickSorted.cpp.s

CMakeFiles/sample.dir/main.cpp.o: CMakeFiles/sample.dir/flags.make
CMakeFiles/sample.dir/main.cpp.o: main.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object CMakeFiles/sample.dir/main.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/sample.dir/main.cpp.o -c /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/main.cpp

CMakeFiles/sample.dir/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sample.dir/main.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/main.cpp > CMakeFiles/sample.dir/main.cpp.i

CMakeFiles/sample.dir/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sample.dir/main.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/main.cpp -o CMakeFiles/sample.dir/main.cpp.s

# Object files for target sample
sample_OBJECTS = \
"CMakeFiles/sample.dir/TestLongestIncreasingSub.cpp.o" \
"CMakeFiles/sample.dir/longestIncreasingSub.cpp.o" \
"CMakeFiles/sample.dir/TestRandomizedQuickSorted.cpp.o" \
"CMakeFiles/sample.dir/RandomizedQuickSorted.cpp.o" \
"CMakeFiles/sample.dir/main.cpp.o"

# External object files for target sample
sample_EXTERNAL_OBJECTS =

sample: CMakeFiles/sample.dir/TestLongestIncreasingSub.cpp.o
sample: CMakeFiles/sample.dir/longestIncreasingSub.cpp.o
sample: CMakeFiles/sample.dir/TestRandomizedQuickSorted.cpp.o
sample: CMakeFiles/sample.dir/RandomizedQuickSorted.cpp.o
sample: CMakeFiles/sample.dir/main.cpp.o
sample: CMakeFiles/sample.dir/build.make
sample: CMakeFiles/sample.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Linking CXX executable sample"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/sample.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/sample.dir/build: sample

.PHONY : CMakeFiles/sample.dir/build

CMakeFiles/sample.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/sample.dir/cmake_clean.cmake
.PHONY : CMakeFiles/sample.dir/clean

CMakeFiles/sample.dir/depend:
	cd /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding /home/qtran/CPLUSPLUS/Cplusplus/AlgorithmsCodingCplusplus/AlgorithmCoding/CMakeFiles/sample.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/sample.dir/depend

